#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  #      base-path: /admin
#  endpoint:
#    health:
#      show-details: always
#info:
#  app:
#    name: Employee Manager Application
#    description: This is an application to manage em.ployees
#    version: 1.0
spring:
  profiles:
    include: db